# Screen Stuff
SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720

#Player Stuff
PLAYER_RADIUS = 20
PLAYER_TURN_SPEED = 300
PLAYER_SPEED = 200
PLAYER_SHOOT_SPEED = 500
PLAYER_SHOOT_CONSTANT = 0.3
PLAYER_RESPAWN_TIME = 0.5 # seconds

# Bullet Stuff
SHOT_RADIUS = 5

# Asteroid Stuff
ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE = 0.8  # seconds
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS